"""add_assistant_app

Revision ID: 3ef9b2b6bee6
Revises: 89c7899ca936
Create Date: 2024-01-05 15:26:25.117551

"""
from ast import Index
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e99a8df00ff'
down_revision = '89c7899ca936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like', sa.Integer, nullable=False,default=0))
        batch_op.add_column(sa.Column('dislike', sa.Integer, nullable=False,default=0))
     

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_queries', schema=None) as batch_op:
        batch_op.drop_column('like')
        batch_op.drop_column('dislike')
    # ### end Alembic commands ###
