"""add_assistant_app

Revision ID: 3ef9b2b6bee6
Revises: 89c7899ca936
Create Date: 2024-01-05 15:26:25.117551

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e99a8df00ff'
down_revision = '89c7899ca936'
branch_labels = None
depends_on = None
# $ flask db stamp head
# $ flask db migrate
# $ flask db upgrade

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_category',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('is_del', sa.Boolean, nullable=False,server_default=sa.text('false')),
    sa.PrimaryKeyConstraint('id', name='app_category_pkey')
    )
    
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cmd', sa.String(128), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(24),nullable=True))
        batch_op.add_column(sa.Column('category_name', sa.String(24),nullable=True))
        batch_op.add_column(sa.Column('func_name', sa.String(32),nullable=True))
        batch_op.add_column(sa.Column('chat_icon', sa.String(256),nullable=True))
        batch_op.add_column(sa.Column('is_robot', sa.Boolean,nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_category')
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('cmd')
        batch_op.drop_column('category')
        batch_op.drop_column('category_name')
        batch_op.drop_column('func_name')
        batch_op.drop_column('chat_icon')
        batch_op.drop_column('is_robot')
    # ### end Alembic commands ###
