"""empty message

Revision ID: ec00da83e4d8
Revises: 4e99a8df00ff
Create Date: 2024-06-18 03:07:43.058216

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec00da83e4d8'
down_revision = '4e99a8df00ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_segments_attachs',
    sa.Column('id', models.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('doc_seg_id', models.StringUUID(), nullable=False),
    sa.Column('attach_type', sa.String(length=10), server_default=sa.text('file'), nullable=True),
    sa.Column('source', sa.String(length=10), server_default=sa.text('url'), nullable=True),
    sa.Column('storage_type', sa.String(length=16), server_default=sa.text('local'), nullable=False),
    sa.Column('file_name', sa.String(length=1024), nullable=False),
    sa.Column('size', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('file', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('extension', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('used_times', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='document_segments_attachs_pkey')
    )
    with op.batch_alter_table('document_segments_attachs', schema=None) as batch_op:
        batch_op.create_index('doc_seg_id_idx', ['doc_seg_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_segments_attachs', schema=None) as batch_op:
        batch_op.drop_index('doc_seg_id_idx')

    op.drop_table('document_segments_attachs')
    # ### end Alembic commands ###
