"""empty message

Revision ID: 9b6a9c9cc42b
Revises: 4e99a8df00ff
Create Date: 2024-06-18 03:22:33.975697

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b6a9c9cc42b'
down_revision = '4e99a8df00ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_category',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('is_del', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='app_category_pkey')
    )
    op.create_table('app_questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('questions', sa.String(length=4096), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('is_virtual', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('status', sa.String(length=255), nullable=False,server_default='indexing'),
    sa.PrimaryKeyConstraint('id', name='app_qur_pkey')
    )
    with op.batch_alter_table('app_questions', schema=None) as batch_op:
        batch_op.create_index('app_qur_app_id_idx', ['app_id'], unique=False)

    op.create_table('document_segments_attachs',
    sa.Column('id', models.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('doc_seg_id', models.StringUUID(), nullable=False),
    sa.Column('attach_type', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=True),
    sa.Column('storage_type', sa.String(length=16), nullable=False),
    sa.Column('file_name', sa.String(length=1024), nullable=False),
    sa.Column('size', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('file', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=256), nullable=False),
    sa.Column('extension', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('used_times', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='document_segments_attachs_pkey')
    )
    with op.batch_alter_table('document_segments_attachs', schema=None) as batch_op:
        batch_op.create_index('doc_seg_id_idx', ['doc_seg_id'], unique=False)

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cmd', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('category_name', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('func_name', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('chat_icon', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('is_robot', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('dataset_queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('seg_ids', sa.JSON, nullable=True))
        # batch_op.add_column(sa.Column('dislike', sa.Integer(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cmd', sa.String(length=24), nullable=True))

    op.create_table('key_words',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('key_word', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='key_words_pkey')
    )
    with op.batch_alter_table('key_words', schema=None) as batch_op:
        batch_op.create_index('key_words_index_domain', ['tenant_id','domain','key_word'], unique=False)

    op.create_table('key_words_closure',
    sa.Column('ancestor_id', sa.UUID(), nullable=False),
    sa.Column('descendant_id', sa.UUID(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('ancestor_id','descendant_id', name='key_words_closure_pkey')
    )
    with op.batch_alter_table('key_words_closure', schema=None) as batch_op:
        batch_op.create_index('key_words_closure_index_tenant', ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('cmd')

    with op.batch_alter_table('dataset_queries', schema=None) as batch_op:
        # batch_op.drop_column('dislike')
        batch_op.drop_column('seg_ids')
        batch_op.drop_column('like')

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('is_robot')
        batch_op.drop_column('chat_icon')
        batch_op.drop_column('func_name')
        batch_op.drop_column('category_name')
        batch_op.drop_column('category')
        batch_op.drop_column('cmd')

    with op.batch_alter_table('document_segments_attachs', schema=None) as batch_op:
        batch_op.drop_index('doc_seg_id_idx')

    op.drop_table('document_segments_attachs')
    with op.batch_alter_table('app_questions', schema=None) as batch_op:
        batch_op.drop_index('app_qur_app_id_idx')

    op.drop_table('app_questions')
    op.drop_table('app_category')
    op.drop_table('key_words')
    op.drop_table('key_words_closure')
    # ### end Alembic commands ###
