"""add wechat app account table

Revision ID: c6e60317e3cc
Revises: 9b6a9c9cc42b
Create Date: 2024-07-30 03:03:08.204471

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e60317e3cc'
down_revision = '9b6a9c9cc42b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wechat_account_app',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('open_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='account_app_pkey')
    )
    with op.batch_alter_table('wechat_account_app', schema=None) as batch_op:
        batch_op.create_index('account_app_accountid_idx', ['account_id'], unique=False)

    with op.batch_alter_table('app_questions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='index-complete',
               existing_nullable=False)

    with op.batch_alter_table('key_words', schema=None) as batch_op:
        batch_op.drop_index('key_words_index_domain')
        batch_op.create_index('key_words_index_domain', ['tenant_id', 'key_word', 'domain'], unique=False)

    with op.batch_alter_table('key_words_closure', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_index('key_words_closure_index_tenant')
        batch_op.create_index('key_words_closure_index_tenant', ['tenant_id'], unique=False)

    op.create_table('wechat_tenant_secret_info',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('wechat_app_id', sa.String(length=255), nullable=False),
    sa.Column('wechat_app_secret', sa.String(length=255), nullable=False),
    sa.Column('app_type', sa.String(length=32), nullable=False,comment="'app,web,open'", server_default=sa.text("'app'::character varying")),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_by', sa.String(length=255), server_default='admin', nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='wechat_tenant_secret_info_pkey')
    )
    with op.batch_alter_table('wechat_tenant_secret_info', schema=None) as batch_op:
        batch_op.create_index('wechat_tenant_secret_info_idx', ['tenant_id'], unique=False)


     # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_batch_hiting_test',
    sa.Column('id', models.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('dataset_id', models.StringUUID(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('param_id', models.StringUUID(), nullable=True),
    sa.Column('like', sa.Integer(), nullable=True),
    sa.Column('dislike', sa.Integer(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True, comment='seg_id,和匹配精度'),
    sa.Column('last_results', sa.JSON(), nullable=True, comment='seg_id,和匹配精度'),
    sa.Column('created_by', models.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='dataset_batch_hiting_test_pkey')
    )
    with op.batch_alter_table('dataset_batch_hiting_test', schema=None) as batch_op:
        batch_op.create_index('dataset_batch_hiting_test_id_idx', ['dataset_id'], unique=False)

    op.create_table('dataset_batch_hiting_test_params',
    sa.Column('id', models.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('dataset_id', models.StringUUID(), nullable=False),
    sa.Column('created_by', models.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='dataset_batch_hiting_test_params_pkey')
    )
    with op.batch_alter_table('dataset_batch_hiting_test_params', schema=None) as batch_op:
        batch_op.create_index('dataset_batch_hiting_test_params_id_idx', ['dataset_id'], unique=False)


    op.create_table('wechat_agent_visible',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('wechat_app_id', sa.String(length=255), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('app_type', sa.String(length=32), server_default='app',comment="'app,web,open'", nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='wechat_agent_visible_pkey')
    )
    with op.batch_alter_table('wechat_agent_visible', schema=None) as batch_op:
        batch_op.create_index('wechat_agent_visible_tenant_idx', ['tenant_id'], unique=False)

    op.create_table('dict_bindings',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('target_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='dict_bindings_pkey')
    )
    op.create_table('dict_category_closure',
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('child_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('parent_id', 'child_id', name='dict_category_closure_pkey')
    )
    op.create_table('dict_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('key', sa.VARCHAR(length=255),  nullable=True),
    sa.Column('type', sa.VARCHAR(length=64),  nullable=False),
    sa.PrimaryKeyConstraint('id', name='dict_categories_pkey')
    )
    
    with op.batch_alter_table('dict_categories', schema=None) as batch_op:
        batch_op.create_index('idx_dict_categories', ['key','type', 'tenant_id'], unique=True)
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key_words_closure', schema=None) as batch_op:
        batch_op.drop_index('key_words_closure_index_tenant')
        batch_op.create_index('key_words_closure_index_tenant', [sa.text('tenant_id DESC')], unique=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('key_words', schema=None) as batch_op:
        batch_op.drop_index('key_words_index_domain')
        batch_op.create_index('key_words_index_domain', ['tenant_id', 'domain', 'key_word'], unique=False)

    with op.batch_alter_table('app_questions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               comment='index-complete',
               existing_nullable=False)

    with op.batch_alter_table('wechat_account_app', schema=None) as batch_op:
        batch_op.drop_index('account_app_accountid_idx')

    op.drop_table('wechat_account_app')

    with op.batch_alter_table('wechat_tenant_secret_info', schema=None) as batch_op:
        batch_op.drop_index('wechat_tenant_secret_info_idx')

    op.drop_table('wechat_tenant_secret_info')
    ######################3
    with op.batch_alter_table('dataset_batch_hiting_test_params', schema=None) as batch_op:
        batch_op.drop_index('dataset_batch_hiting_test_params_id_idx')

    op.drop_table('dataset_batch_hiting_test_params')
    with op.batch_alter_table('dataset_batch_hiting_test', schema=None) as batch_op:
        batch_op.drop_index('dataset_batch_hiting_test_id_idx')

    op.drop_table('dataset_batch_hiting_test')

    with op.batch_alter_table('wechat_agent_visible', schema=None) as batch_op:
        batch_op.drop_index('wechat_agent_visible_tenant_idx')

    op.drop_table('wechat_agent_visible')
    #### 字典表
    op.drop_table('dict_bindings')
    op.drop_table('dict_category_closure')
    op.drop_table('dict_categories')
    # ### end Alembic commands ###
